FROM adoptopenjdk/openjdk11:latest
ENV KEYCLOAK_CLIENT null
ENV KEYCLOAK_REALM null
ENV DB_URL null
ENV DB_USER null
ENV DB_PASSWORD null
ENV KEYCLOAK_URL null
ENV KEYCLOAK_SECRET null
ENV CLOUDKARAFKA_TOPIC_PREFIX null
ENV CLOUDKARAFKA_BROKERS null
ENV CLOUDKARAFKA_USERNAME null
ENV CLOUDKARAFKA_PASSWORD null

ARG JAR_FILE=build/libs/alert-covid-service-kafka-*.jar


WORKDIR /opt/app

COPY ${JAR_FILE} service_kafka.jar
EXPOSE 9000
ENTRYPOINT java -DKEYCLOAK_CLIENT=$KEYCLOAK_CLIENT -DKEYCLOAK_REALM=$KEYCLOAK_REALM -DDB_URL=$DB_URL -DDB_USER=$DB_USER -DDB_PASSWORD=$DB_PASSWORD -DKEYCLOAK_URL=$KEYCLOAK_URL -DKEYCLOAK_SECRET=$KEYCLOAK_SECRET -DCLOUDKARAFKA_TOPIC_PREFIX=$CLOUDKARAFKA_TOPIC_PREFIX -DCLOUDKARAFKA_BROKERS=$CLOUDKARAFKA_BROKERS -DCLOUDKARAFKA_USERNAME=$CLOUDKARAFKA_USERNAME -DCLOUDKARAFKA_PASSWORD=$CLOUDKARAFKA_PASSWORD -jar service_kafka.jar
